#ifndef __ImageCorrectionsFrame__
#define __ImageCorrectionsFrame__

/**
@file
Subclass of Frame, which is generated by wxFormBuilder.
*/

#include "ImageCorrections.h"

//// end generated include
#include <memory>
#include <wx/dcclient.h>
#include <wx/wx.h>
#include <wx/colour.h>
#include <wx/colordlg.h>
#include <wx/dcbuffer.h>

/** Implementing Frame */
class ImageCorrectionsFrame : public Frame
{
protected:
	// Handlers for Frame events.
	void image_BoxOnUpdateUI(wxUpdateUIEvent& event);
	void color_Hexagon_BoxOnLeftDClick(wxMouseEvent& event);
	void chanel_choiceOnUpdateUI(wxUpdateUIEvent& event);
	void slider_ChangeCoefficientOnScroll(wxScrollEvent& event);
	void slider_MixImagesOnScroll(wxScrollEvent& event);
	void menu_File_OpenOnMenuSelection(wxCommandEvent& event);
	void menu_File_SaveOnMenuSelection(wxCommandEvent& event);
	void menu_File_ExitOnMenuSelection(wxCommandEvent& event);
	void menu_About_InfoOnMenuSelection(wxCommandEvent& event);
	void Contrast(int value);
	void Brightness(int value);
	void Barwa(int value);
	void Saturation(int value);
public:
	/** Constructor */
	ImageCorrectionsFrame(wxWindow* parent);
	//// end generated class members
	void Repaint();

private:
	wxImage Img_Org, // original image
		Img_Cpy; // copy image
	wxImage::HSVValue Img_HSV;
	wxImage::RGBValue Img_RGB;


};

#endif // __ImageCorrectionsFrame__
